[package]
name = "hbc"
version = "0.1.0"
edition = "2021"
description = ""
license = "GPL-3.0"
keywords = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pyu_rust_util = "0.1.66"
